version: '3'

services:
  mediathekview:
    build: .
    container_name: mediathekview
    ports:
      - "5800:5800"
    volumes:
      - "$MV_CONFIG_PATH:/config:rw"
      - "$MV_OUTPUT_PATH:/output:rw"
    environment:
       - "USER_ID=1000"
       - "GROUP_ID=100"
